package com.vishwasa.enums;

public enum CaseStatus {
    DRAFT,
    SUBMITTED,
    IDENTITY_VERIFICATION,
    FIELD_VERIFICATION,
    MEDICAL_REVIEW,
    HOSPITAL_ESTIMATE,
    APPROVED,
    FUNDRAISING,
    FUNDING_COMPLETE,
    TREATMENT_STARTED,
    TREATMENT_COMPLETED,
    FOLLOW_UP,
    CLOSED,
    REJECTED,
    CANCELLED,
    MORE_INFORMATION_REQUIRED
}
